# Generated by Django 4.2.8 on 2023-12-07 14:03

from django.db import migrations, models
import django.db.models.deletion
import django_jsonform.models.fields
import imagekit.models.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Quest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200, unique=True, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "sum_rules",
                    django_jsonform.models.fields.JSONField(
                        blank=True, default=None, null=True, verbose_name="Результирующие правила"
                    ),
                ),
                ("cover", imagekit.models.fields.ProcessedImageField(blank=True, upload_to="covers")),
                ("hidden", models.BooleanField(default=True, verbose_name="Скрытый")),
            ],
            options={
                "verbose_name": "Квест",
                "verbose_name_plural": "Квесты",
            },
        ),
        migrations.CreateModel(
            name="Step",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("text", models.TextField()),
                ("cover", models.ImageField(blank=True, upload_to="covers")),
                ("quest", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.quest")),
            ],
            options={
                "verbose_name": "Шаг",
                "verbose_name_plural": "Шаги",
            },
        ),
        migrations.AddField(
            model_name="quest",
            name="initial_step",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="initial_step",
                to="api.step",
                verbose_name="Начальный шаг",
            ),
        ),
        migrations.CreateModel(
            name="Option",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.TextField(verbose_name="Текст")),
                ("after_text", models.TextField(blank=True, verbose_name="Текст после ответа")),
                ("after_cover", imagekit.models.fields.ProcessedImageField(blank=True, upload_to="covers")),
                (
                    "next_step",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="next_step",
                        to="api.step",
                        verbose_name="Следующий шаг",
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="api.step",
                        verbose_name="Шаг",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вариант ответа",
                "verbose_name_plural": "Варианты ответа",
            },
        ),
        migrations.CreateModel(
            name="CompletedStats",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("telegram_user", models.IntegerField(verbose_name="Telegram ID пользователя")),
                ("started_at", models.DateTimeField(auto_now_add=True, verbose_name="Начат")),
                ("finished_at", models.DateTimeField(blank=True, null=True, verbose_name="Завершен")),
                (
                    "quest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.quest", verbose_name="Квест"
                    ),
                ),
            ],
            options={
                "verbose_name": "Прохождения",
                "verbose_name_plural": "Прохождения",
            },
        ),
        migrations.AddConstraint(
            model_name="quest",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("initial_step__isnull", True), ("hidden", True)),
                    ("initial_step__isnull", False),
                    _connector="OR",
                ),
                name="Условия показа квеста (указан начальный шаг)",
            ),
        ),
    ]
