# Generated by Django 4.2.8 on 2023-12-07 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="completedstats",
            old_name="telegram_user",
            new_name="telegram_id",
        ),
        migrations.CreateModel(
            name="QuestLike",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("telegram_id", models.IntegerField(verbose_name="Telegram ID пользователя")),
                (
                    "quest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.quest", verbose_name="Квест"
                    ),
                ),
            ],
            options={
                "verbose_name": "Лайк",
                "verbose_name_plural": "Лайки",
                "unique_together": {("telegram_id", "quest")},
            },
        ),
    ]
