# Generated by Django 4.2.8 on 2023-12-07 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_rename_telegram_user_completedstats_telegram_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="step",
            name="quest",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="steps", to="api.quest", verbose_name="Квест"
            ),
        ),
    ]
